mqtt: 
    client_id: "gateway001"
    broker_ip: "my-mosquitto-broker"
    broker_port: 1883
    topic: "service/control/track_points"
http: 
    host: "0.0.0.0"
    port: 7072
    rest_prefix: "/gateway/"
