broker_ip: "my-mosquitto-broker"
broker_port: 1883
target_telemetry_topic: "service/flock_localization/flock_center"
target_telemetry_d_topic: "service/flock_localization/drones_center_gps"
target_environment_topic: "service/sys_monitoring/env"
target_info_topic: "drone/+/info"
device_api_url: "http://http-inventory-api:7070/api/v1/iot/inventory/position/flock_center"
drones_center_api_url: "http://http-inventory-api:7070/api/v1/iot/inventory/position/drones_center"
environment_api_url: "http://http-inventory-api:7070/api/v1/iot/inventory/environment"
info_api_url: "http://http-inventory-api:7070/api/v1/iot/inventory"